### ISSUE TITLE
Create directory before downloading JSON and cover art

### ISSUE THREAD

**Issue by nemec** [RaduTek/YTMusicDL#1]
When writing songs to a nested directory (e.g. `ytmusic/{album_artist|song_artist}/{album_title|song_title}/{song_index|+ - }{song_title} [{song_id}].{ext}`) the intermediate directories are not created before attempting to download the JSON metadata and cover art if they don't exist. This causes the metadata download to fail. The directories are created when the song is downloaded -- I assume that's part of `YoutubeDL` -- so in this example you'd lose metadata for the first song in each artist's album.

It's a pretty easy fix. On [line 901](https://github.com/RaduTek/YTMusicDL/blob/master/ytmusicdl.py#L900-L902) add the following:

```python
directory = os.path.dirname(out_file_ext)
if not os.path.exists(directory):
    os.makedirs(directory)
```

**Comment by nemec** [comment]
Thanks for writing this, btw. I was looking for a new downloader since Google Play Music went away 👍

**Comment by RaduTek** [comment]
Thanks for finding this bug!

I used these arguments to replicate the issue: `python .\ytmusicdl.py --skip-download --write-cover --write-json -p "test" -o "{album_artist|song_artist}/{album_title|song_title}/{song_index|+ - }{song_title} [{song_id}].{ext}" <Test playlist ID goes here>`

I've added your fix here: https://github.com/RaduTek/YTMusicDL/commit/54b88fd181ebe9ca8f25ecb365cef2f660c7ab41
